create table equipment (
    id            bigint generated by default as identity primary key,
    type          varchar(255) not null,
    site          varchar(255) not null,
    status        varchar(16)  not null,
    registered_at timestamptz  not null
);

create table usage_event (
    id           bigint generated by default as identity primary key,
    equipment_id bigint      not null references equipment (id),
    status       varchar(16) not null,
    occurred_at  timestamptz not null
);

create index idx_usage_event_equipment_ts on usage_event (equipment_id, occurred_at);

create table daily_report (
    id           bigint generated by default as identity primary key,
    report_date  date             not null,
    equipment_id bigint           references equipment (id),
    scope_key    varchar(64)      not null,
    utilization  double precision not null,
    uptime       double precision not null,
    computed_at  timestamptz      not null,
    constraint uq_daily_report_day_scope unique (report_date, scope_key)
);

create index idx_daily_report_date on daily_report (report_date);
